# -*- coding: utf-8 -*-
"""Python Notebook(Jenkins).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UrJygYPBm5MoTtDt6TrZoQ2k6GPwuh0
"""

l = [2,4,6,8,10]
square = [i**2 for i in l]
print('square of the numbers are:', square)
cube = [i**3 for i in l]
print('cube of the numbers are:',cube)

